# Site settings
title: Hasan Balcı & Leonard Dervishi \n Analyzing ICIJ Offshore Leaks Database with Clustering and Graph Algorithms
author: Hasan Balcı & Leonard Dervishi
#author_avatar: https://gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=50
email: alias@domain.tld
description: Blog about whatever.
baseurl: "/CS578" # optional
url: "https://leonarddrv.github.io/CS578/"
#twitter_username: foo_bar
#github_username: foo_bar
#github_repo: foo_bar/foo_bar.github.io
#google_analytics: UA-80085-YOUR-ID
disqus: leonarddrv-github-io-cs578

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"
variables:
        page.author_footer: true
gems:
  - jekyll-sitemap
